clients/TestSite/config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/index'

  resources :posts
  resources :categories

end

clients/TestSite/app/models/category.rb
class Category < ActiveRecord::Base
    has_many :posts
end

clients/TestSite/app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :category
end

clients/TestSite/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    def index
        @categories = Category.all
    end

    def show
        @category = Category.find(params[:id])
		@title = @category.name
		@posts = @category.posts
    end


    def create
        @category = Category.create(location_params)
    end

    def update
        category = Category.find(params[:id])
        category = Category.update_attributes!(category_params)
        redirect_to category
    end


    private

    def category_params
        params.require(:category).permit(:name)
    end
end

clients/TestSite/app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
        @posts = Post.all
    end


    def new
        @post = Post.new
        @category = Category.all
    end


    def create
        @post = Post.new(post_params)
        if @post.save
            redirect_to posts_path, :notice => "Your post has been saved"
        else
            render "new"
        end
    end

    
    def edit
        @post = Post.find(params[:id]) 
    end


    def update
        @post = Post.find(params[:id]) 

        if @post.update_attributes(post_params)
            redirect_to post_path, :notice => "Your post has been updated"
        else
            render "edit" 
        end
    end


    def show
        @post = Post.find(params[:id]) 
    end


    def destroy
        @post = Post.find(params[:id]) 
        @post.destroy
        redirect_to posts_path, :notice => "Your post has been deleted"
    end


    private

    def post_params
        params.require(:post).permit(:title, :body, :category_id, :author_id)
    end
end

clients/TestSite/app/helpers/categories_helper.rb
module CategoriesHelper
end

clients/TestSite/app/helpers/posts_helper.rb
module PostsHelper
end

clients/TestSite/app/views/categories/edit.html.erb
<h1>Edit Category</h1>

clients/TestSite/app/views/categories/index.html.erb
<h1>Category Index</h1>

<ul>
    <% @categories.each do |category| %>
		<li><%= link_to category.name, category %></li>
    <% end %>
</ul>

clients/TestSite/app/views/categories/new.html.erb
<h1>New Category</h1>

clients/TestSite/app/views/categories/show.html.erb
<h1><%= @category.name %></h1>
<% if @posts.each do |post| %>
	<h3><%= link_to post.title, post %></h3>	
	<p><%= post.body %></p>
<% end.empty? %>
	<p>Sorry, there are no posts in this category</p>
<% end %>

<%= link_to "Back to Categories", categories_path %>

clients/TestSite/app/views/home/index.html.erb
<h1>Such a great homepage</h1>
<p>So, you made it this far...Good!</p>

clients/TestSite/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestSite</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

clients/TestSite/app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= form_for @post do |f| %>
    <p>
        <%= f.label :title %><br />
        <%= f.text_field :title %><br />
    </p>
    <p>
        <%= f.label :body %><br />
        <%= f.text_area :body %><br />
    </p>
    <p>
        <%= f.select :category_id, Category.all.collect {|x| [x.name, x.id]}, {:include_blank => "Select One"} %><br />
    </p>
    <p>
        <%= f.submit "Update Post" %>
    </p>
<% end %>

<%= link_to "Go Back", post_path %>

clients/TestSite/app/views/posts/index.html.erb
<h1>Blog Post</h1>
<%= link_to "Create New Post", new_post_path %>

<% @posts.each do |post| %>
    <h3><%= link_to post.title, post %></h3>
    <p><%= post.body %>
    <hr>   
<% end %>

clients/TestSite/app/views/posts/new.html.erb
<h1>Add New Post</h1>
<%= form_for @post do |f| %>
    <p>
        <%= f.label :title %><br />
        <%= f.text_field :title %><br />
    </p>
    <p>
        <%= f.label :body %><br />
        <%= f.text_area :body %><br />
    </p>

    <p>
        <%= f.select :category_id, Category.all.collect {|x| [x.name, x.id]}, {:include_blank => "Select One"} %><br />
    </p>
    <p>
        <%= f.submit "Add Post" %>
    </p>
<% end %>

clients/TestSite/app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<small><%= @post.created_at.strftime("%b %d. %Y") %></small>
<p><%= @post.body %></p>
<p>Category: <%= link_to @post.category.name, category_path(:id => @post.category.id) %></p>
<%= link_to "Edit Post", edit_post_path %>
|
<%= link_to "Delete Post", @post, :method => :delete, data: {confirm: "Are you sure you want to delete?"} %>
|
<%= link_to "View All Posts", posts_path %>